### ISSUE TITLE
"Execute Store" arguments are wrong

### ISSUE THREAD

**Issue by cowslayer7890** [MrYurihi/mcfunction#3]
the tab completion says `execute store (result/success) name objective -> execute` is the syntax for `execute store`, when really it is either `execute store (result/success) score name objective -> execute` or `execute store (result/success) (entity/block) (name/pos) path type scale -> execute`

**Comment by MrYurihi** [comment]
Could you create a fork, then fix the issue, then pull request? I'm busy currently, so I don't have much time

**Comment by cowslayer7890** [comment]
idk how to write packages for atom lmao sorry.
